imports:
  - { resource: demo.yml }

parameters:
  beyerz_aws_queue.producer_service.class: Beyerz\AWSQueueBundle\Service\ProducerService
  beyerz_aws_queue.fabric.aws.class: Beyerz\AWSQueueBundle\Fabric\Aws\SnsSqs\Fabric
  beyerz_aws_queue.fabric.gearman.class: Beyerz\AWSQueueBundle\Fabric\GearmanFabric
  beyerz_aws_queue.fabric.local.class: Beyerz\AWSQueueBundle\Fabric\LocalFabric

services:

  beyerz_aws_queue.producer_service:
    class: "%beyerz_aws_queue.producer_service.class%"
    arguments: ["@beyerz_aws_queue.fabric.local","default_channel"]
    public: false

  beyerz_aws_queue.fabric.aws.sns_sqs:
    class: "%beyerz_aws_queue.fabric.aws.class%"
    arguments: ["%beyerz_aws_queue.aws.region%","%beyerz_aws_queue.aws.account%","@aws.sns","@aws.sqs"]
    public: false

  beyerz_aws_queue.fabric.local:
    class: "%beyerz_aws_queue.fabric.local.class%"
    calls:
      - [setContainer, ['@service_container']]