language: php
sudo: false

php:
- 7.0
- 7.1
- 7.2

env:
- SYMFONY_VERSION=2.8.*
- SYMFONY_VERSION=3.0.*
- SYMFONY_VERSION=3.1.*
- SYMFONY_VERSION=3.2.*
- SYMFONY_VERSION=3.3.*

cache:
  directories:
  - $HOME/.composer/cache

before_install:
- composer self-update
- if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install:
- composer install

script:
- ./vendor/bin/phpunit