<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIgf9uu7\appTestDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIgf9uu7/appTestDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIgf9uu7.legacy');

    return;
}

if (!\class_exists(appTestDebugProjectContainer::class, false)) {
    \class_alias(\ContainerIgf9uu7\appTestDebugProjectContainer::class, appTestDebugProjectContainer::class, false);
}

return new \ContainerIgf9uu7\appTestDebugProjectContainer(array(
    'container.build_hash' => 'Igf9uu7',
    'container.build_id' => '0081aa17',
    'container.build_time' => 1548170976,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerIgf9uu7');
