<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'beyerz_aws_queue.test.producer.local' shared service.

$this->services['beyerz_aws_queue.test.producer.local'] = $instance = new \Beyerz\AWSQueueBundle\Demo\Producer();

$instance->setProducerService(${($_ = isset($this->services['beyerz_aws_queue.producer_service.test_producer']) ? $this->services['beyerz_aws_queue.producer_service.test_producer'] : $this->load('getBeyerzAwsQueue_ProducerService_TestProducerService.php')) && false ?: '_'});

return $instance;
