<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'beyerz_aws_queue.consumer_service.beyerz_test_channel' shared service.

$this->services['beyerz_aws_queue.consumer_service.beyerz_test_channel'] = $instance = new \Beyerz\AWSQueueBundle\Consumer\ConsumerService(${($_ = isset($this->services['beyerz_aws_queue.fabric.local']) ? $this->services['beyerz_aws_queue.fabric.local'] : $this->load('getBeyerzAwsQueue_Fabric_LocalService.php')) && false ?: '_'}, 'test_beyerz_test_channel', array(0 => 'test_producer'));

$instance->setConsumer(new \Beyerz\AWSQueueBundle\Tests\Unit\Fabric\Consumer());
$instance->setContainer($this);

return $instance;
