<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'beyerz_aws_queue.fabric.local' shared service.

$this->services['beyerz_aws_queue.fabric.local'] = $instance = new \Beyerz\AWSQueueBundle\Fabric\LocalFabric();

$instance->setContainer($this);

return $instance;
