<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'beyerz_aws_queue.demo.producer.1' shared service.

$this->services['beyerz_aws_queue.demo.producer.1'] = $instance = new \Beyerz\AWSQueueBundle\Demo\Producer();

$instance->setProducerService(${($_ = isset($this->services['beyerz_aws_queue.producer_service.demo']) ? $this->services['beyerz_aws_queue.producer_service.demo'] : $this->load('getBeyerzAwsQueue_ProducerService_DemoService.php')) && false ?: '_'});

return $instance;
