<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'beyerz_aws_queue.test.consumer.local' shared service.

return $this->services['beyerz_aws_queue.test.consumer.local'] = new \Beyerz\AWSQueueBundle\Tests\Unit\Fabric\Consumer();
