<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'beyerz_aws_queue.consumer_service.beyerz_demo' shared service.

$this->services['beyerz_aws_queue.consumer_service.beyerz_demo'] = $instance = new \Beyerz\AWSQueueBundle\Consumer\ConsumerService(${($_ = isset($this->services['beyerz_aws_queue.fabric.local']) ? $this->services['beyerz_aws_queue.fabric.local'] : $this->load('getBeyerzAwsQueue_Fabric_LocalService.php')) && false ?: '_'}, 'test_beyerz_demo', array(0 => 'demo', 1 => 'demo_producer_2'));

$instance->setConsumer(new \Beyerz\AWSQueueBundle\Demo\Consumer());
$instance->setContainer($this);

return $instance;
