<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'beyerz_aws_queue.demo.consumer' shared service.

return $this->services['beyerz_aws_queue.demo.consumer'] = new \Beyerz\AWSQueueBundle\Demo\Consumer();
