<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'var_dumper.cloner' shared service.

$this->services['var_dumper.cloner'] = $instance = new \Symfony\Component\VarDumper\Cloner\VarCloner();

$instance->setMaxItems(2500);
$instance->setMinDepth(1);
$instance->setMaxString(-1);

return $instance;
